// This file is autogenerated. Do not modify
package controllers

import (
	"errors"
	"io/ioutil"
	"net/http"

	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi/interfaces"
)

type captureController struct {
	handler interfaces.CaptureHandler
}

func NewHttpCaptureController(handler interfaces.CaptureHandler) interfaces.CaptureController {
	return &captureController{handler}
}

func (ctrl *captureController) Routes() []httpapi.Route {
	return []httpapi.Route{
		{Path: "/results/capture", Method: "POST", Name: "GetCapture", Handler: ctrl.GetCapture},
	}
}

/*
GetCapture: POST /results/capture
Description:
*/
func (ctrl *captureController) GetCapture(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.CaptureRequest
	if r.Body != nil {
		body, readError := ioutil.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewCaptureRequest()
			err := item.FromJson(string(body))
			if err != nil {
				ctrl.responseGetCapture400(w, err)
				return
			}
		} else {
			ctrl.responseGetCapture400(w, readError)
			return
		}
	} else {
		bodyError := errors.New("Request do not have any body")
		ctrl.responseGetCapture400(w, bodyError)
		return
	}
	result := ctrl.handler.GetCapture(item, r)
	if result.HasStatusCode200() {
		httpapi.WriteByteResponse(w, 200, result.StatusCode200())
		return
	}
	if result.HasStatusCode400() {
		httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
		return
	}
	if result.HasStatusCode500() {
		httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
		return
	}
	httpapi.WriteDefaultResponse(w, http.StatusInternalServerError)
}

func (ctrl *captureController) responseGetCapture400(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewGetCaptureResponse()
	result.StatusCode400().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 400, result.StatusCode500())
}

func (ctrl *captureController) responseGetCapture500(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewGetCaptureResponse()
	result.StatusCode500().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
}
