// This file is autogenerated. Do not modify
package controllers

import (
	"errors"
	"io/ioutil"
	"net/http"

	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi/interfaces"
	"google.golang.org/protobuf/encoding/protojson"
)

type configurationController struct {
	handler interfaces.ConfigurationHandler
}

func NewHttpConfigurationController(handler interfaces.ConfigurationHandler) interfaces.ConfigurationController {
	return &configurationController{handler}
}

func (ctrl *configurationController) Routes() []httpapi.Route {
	return []httpapi.Route{
		{Path: "/config", Method: "POST", Name: "SetConfig", Handler: ctrl.SetConfig},
		{Path: "/config", Method: "GET", Name: "GetConfig", Handler: ctrl.GetConfig},
	}
}

var configurationMrlOpts = protojson.MarshalOptions{
	UseProtoNames:   true,
	AllowPartial:    true,
	EmitUnpopulated: true,
	Indent:          "  ",
}

/*
SetConfig: POST /config
Description: Sets configuration resources on the traffic generator.
*/
func (ctrl *configurationController) SetConfig(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.Config
	if r.Body != nil {
		body, readError := ioutil.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewConfig()
			err := item.FromJson(string(body))
			if err != nil {
				ctrl.responseSetConfig400(w, err)
				return
			}
		} else {
			ctrl.responseSetConfig400(w, readError)
			return
		}
	} else {
		bodyError := errors.New("Request do not have any body")
		ctrl.responseSetConfig400(w, bodyError)
		return
	}
	result := ctrl.handler.SetConfig(item, r)
	if result.HasStatusCode400() {
		httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
		return
	}
	if result.HasStatusCode500() {
		httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
		return
	}
	data, err := configurationMrlOpts.Marshal(result.StatusCode200().Msg())
	if err != nil {
		ctrl.responseSetConfig400(w, err)
	}
	httpapi.WriteCustomJSONResponse(w, 200, data)

}

func (ctrl *configurationController) responseSetConfig400(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewSetConfigResponse()
	result.StatusCode400().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
}

func (ctrl *configurationController) responseSetConfig500(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewSetConfigResponse()
	result.StatusCode500().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
}

/*
GetConfig: GET /config
Description:
*/
func (ctrl *configurationController) GetConfig(w http.ResponseWriter, r *http.Request) {
	result := ctrl.handler.GetConfig(r)
	if result.HasStatusCode400() {
		httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
		return
	}
	if result.HasStatusCode500() {
		httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
		return
	}
	httpapi.WriteJSONResponse(w, 200, result.StatusCode200())
}

func (ctrl *configurationController) responseGetConfig400(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewGetConfigResponse()
	result.StatusCode400().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
}

func (ctrl *configurationController) responseGetConfig500(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewGetConfigResponse()
	result.StatusCode500().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
}
