// This file is autogenerated. Do not modify
package controllers

import (
	"errors"
	"io/ioutil"
	"net/http"

	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi/interfaces"
	"google.golang.org/protobuf/encoding/protojson"
)

type controlController struct {
	handler interfaces.ControlHandler
}

func NewHttpControlController(handler interfaces.ControlHandler) interfaces.ControlController {
	return &controlController{handler}
}

func (ctrl *controlController) Routes() []httpapi.Route {
	return []httpapi.Route{
		{Path: "/control/transmit", Method: "POST", Name: "SetTransmitState", Handler: ctrl.SetTransmitState},
		{Path: "/control/link", Method: "POST", Name: "SetLinkState", Handler: ctrl.SetLinkState},
		{Path: "/control/capture", Method: "POST", Name: "SetCaptureState", Handler: ctrl.SetCaptureState},
		{Path: "/control/flows", Method: "POST", Name: "UpdateFlows", Handler: ctrl.UpdateFlows},
		{Path: "/control/routes", Method: "POST", Name: "SetRouteState", Handler: ctrl.SetRouteState},
		{Path: "/control/ping", Method: "POST", Name: "SendPing", Handler: ctrl.SendPing},
		{Path: "/control/protocols", Method: "POST", Name: "SetProtocolState", Handler: ctrl.SetProtocolState},
	}
}

/*
SetTransmitState: POST /control/transmit
Description: Updates the state of configuration resources on the traffic generator.
*/
func (ctrl *controlController) SetTransmitState(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.TransmitState
	if r.Body != nil {
		body, readError := ioutil.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewTransmitState()
			err := item.FromJson(string(body))
			if err != nil {
				ctrl.responseSetTransmitState400(w, err)
				return
			}
		} else {
			ctrl.responseSetTransmitState400(w, readError)
			return
		}
	} else {
		bodyError := errors.New("Request do not have any body")
		ctrl.responseSetTransmitState400(w, bodyError)
		return
	}
	result := ctrl.handler.SetTransmitState(item, r)
	if result.HasStatusCode200() {
		opts := protojson.MarshalOptions{
			UseProtoNames:   true,
			AllowPartial:    true,
			EmitUnpopulated: true,
			Indent:          "  ",
		}
		data, err := opts.Marshal(result.StatusCode200().Msg())
		if err != nil {
			ctrl.responseSetTransmitState400(w, err)
		}
		httpapi.WriteCustomJSONResponse(w, 200, data)
		return
	}

	if result.HasStatusCode400() {
		httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
		return
	}
	if result.HasStatusCode500() {
		httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
		return
	}
	httpapi.WriteDefaultResponse(w, http.StatusInternalServerError)
}

func (ctrl *controlController) responseSetTransmitState400(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewSetTransmitStateResponse()
	result.StatusCode400().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
}

func (ctrl *controlController) responseSetTransmitState500(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewSetTransmitStateResponse()
	result.StatusCode500().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
}

/*
SetLinkState: POST /control/link
Description: Updates the state of configuration resources on the traffic generator.
*/
func (ctrl *controlController) SetLinkState(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.LinkState
	if r.Body != nil {
		body, readError := ioutil.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewLinkState()
			err := item.FromJson(string(body))
			if err != nil {
				ctrl.responseSetLinkState400(w, err)
				return
			}
		} else {
			ctrl.responseSetLinkState400(w, readError)
			return
		}
	} else {
		bodyError := errors.New("Request do not have any body")
		ctrl.responseSetLinkState400(w, bodyError)
		return
	}
	result := ctrl.handler.SetLinkState(item, r)
	if result.HasStatusCode200() {
		opts := protojson.MarshalOptions{
			UseProtoNames:   true,
			AllowPartial:    true,
			EmitUnpopulated: true,
			Indent:          "  ",
		}
		data, err := opts.Marshal(result.StatusCode200().Msg())
		if err != nil {
			ctrl.responseSetLinkState400(w, err)
		}
		httpapi.WriteCustomJSONResponse(w, 200, data)
		return
	}

	if result.HasStatusCode400() {
		httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
		return
	}
	if result.HasStatusCode500() {
		httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
		return
	}
	httpapi.WriteDefaultResponse(w, http.StatusInternalServerError)
}

func (ctrl *controlController) responseSetLinkState400(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewSetLinkStateResponse()
	result.StatusCode400().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
}

func (ctrl *controlController) responseSetLinkState500(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewSetLinkStateResponse()
	result.StatusCode500().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
}

/*
SetCaptureState: POST /control/capture
Description: Updates the state of configuration resources on the traffic generator.
*/
func (ctrl *controlController) SetCaptureState(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.CaptureState
	if r.Body != nil {
		body, readError := ioutil.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewCaptureState()
			err := item.FromJson(string(body))
			if err != nil {
				ctrl.responseSetCaptureState400(w, err)
				return
			}
		} else {
			ctrl.responseSetCaptureState400(w, readError)
			return
		}
	} else {
		bodyError := errors.New("Request do not have any body")
		ctrl.responseSetCaptureState400(w, bodyError)
		return
	}
	result := ctrl.handler.SetCaptureState(item, r)
	if result.HasStatusCode200() {
		opts := protojson.MarshalOptions{
			UseProtoNames:   true,
			AllowPartial:    true,
			EmitUnpopulated: true,
			Indent:          "  ",
		}
		data, err := opts.Marshal(result.StatusCode200().Msg())
		if err != nil {
			ctrl.responseSetCaptureState400(w, err)
		}
		httpapi.WriteCustomJSONResponse(w, 200, data)
		return
	}

	if result.HasStatusCode400() {
		httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
		return
	}
	if result.HasStatusCode500() {
		httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
		return
	}
	httpapi.WriteDefaultResponse(w, http.StatusInternalServerError)
}

func (ctrl *controlController) responseSetCaptureState400(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewSetCaptureStateResponse()
	result.StatusCode400().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
}

func (ctrl *controlController) responseSetCaptureState500(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewSetCaptureStateResponse()
	result.StatusCode500().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
}

/*
UpdateFlows: POST /control/flows
Description: Updates flow properties without disruption of transmit state.
*/
func (ctrl *controlController) UpdateFlows(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.FlowsUpdate
	if r.Body != nil {
		body, readError := ioutil.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewFlowsUpdate()
			err := item.FromJson(string(body))
			if err != nil {
				ctrl.responseUpdateFlows400(w, err)
				return
			}
		} else {
			ctrl.responseUpdateFlows400(w, readError)
			return
		}
	} else {
		bodyError := errors.New("Request do not have any body")
		ctrl.responseUpdateFlows400(w, bodyError)
		return
	}
	result := ctrl.handler.UpdateFlows(item, r)
	if result.HasStatusCode200() {
		httpapi.WriteJSONResponse(w, 200, result.StatusCode200())
		return
	}
	if result.HasStatusCode400() {
		httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
		return
	}
	if result.HasStatusCode500() {
		httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
		return
	}
	httpapi.WriteDefaultResponse(w, http.StatusInternalServerError)
}

func (ctrl *controlController) responseUpdateFlows400(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewUpdateFlowsResponse()
	result.StatusCode400().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
}

func (ctrl *controlController) responseUpdateFlows500(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewUpdateFlowsResponse()
	result.StatusCode500().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
}

/*
SetRouteState: POST /control/routes
Description: Updates the state of configuration resources on the traffic generator.
*/
func (ctrl *controlController) SetRouteState(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.RouteState
	if r.Body != nil {
		body, readError := ioutil.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewRouteState()
			err := item.FromJson(string(body))
			if err != nil {
				ctrl.responseSetRouteState400(w, err)
				return
			}
		} else {
			ctrl.responseSetRouteState400(w, readError)
			return
		}
	} else {
		bodyError := errors.New("Request do not have any body")
		ctrl.responseSetRouteState400(w, bodyError)
		return
	}
	result := ctrl.handler.SetRouteState(item, r)
	if result.HasStatusCode200() {
		opts := protojson.MarshalOptions{
			UseProtoNames:   true,
			AllowPartial:    true,
			EmitUnpopulated: true,
			Indent:          "  ",
		}
		data, err := opts.Marshal(result.StatusCode200().Msg())
		if err != nil {
			ctrl.responseSetRouteState400(w, err)
		}
		httpapi.WriteCustomJSONResponse(w, 200, data)
		return
	}

	if result.HasStatusCode400() {
		httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
		return
	}
	if result.HasStatusCode500() {
		httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
		return
	}
	httpapi.WriteDefaultResponse(w, http.StatusInternalServerError)
}

func (ctrl *controlController) responseSetRouteState400(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewSetRouteStateResponse()
	result.StatusCode400().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
}

func (ctrl *controlController) responseSetRouteState500(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewSetRouteStateResponse()
	result.StatusCode500().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
}

/*
SendPing: POST /control/ping
Description: API to send an IPv4 and/or IPv6 ICMP Echo Request(s) between endpoints. For each endpoint 1 ping packet will be sent and API shall wait for ping response to either be successful or timeout. The API wait timeout for each request is 300ms.
*/
func (ctrl *controlController) SendPing(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.PingRequest
	if r.Body != nil {
		body, readError := ioutil.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewPingRequest()
			err := item.FromJson(string(body))
			if err != nil {
				ctrl.responseSendPing400(w, err)
				return
			}
		} else {
			ctrl.responseSendPing400(w, readError)
			return
		}
	} else {
		bodyError := errors.New("Request do not have any body")
		ctrl.responseSendPing400(w, bodyError)
		return
	}
	result := ctrl.handler.SendPing(item, r)
	if result.HasStatusCode200() {
		httpapi.WriteJSONResponse(w, 200, result.StatusCode200())
		return
	}
	if result.HasStatusCode400() {
		httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
		return
	}
	if result.HasStatusCode500() {
		httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
		return
	}
	httpapi.WriteDefaultResponse(w, http.StatusInternalServerError)
}

func (ctrl *controlController) responseSendPing400(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewSendPingResponse()
	result.StatusCode400().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
}

func (ctrl *controlController) responseSendPing500(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewSendPingResponse()
	result.StatusCode500().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
}

/*
SetProtocolState: POST /control/protocols
Description: Sets all configured protocols to `start` or `stop` state.
*/
func (ctrl *controlController) SetProtocolState(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.ProtocolState
	if r.Body != nil {
		body, readError := ioutil.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewProtocolState()
			err := item.FromJson(string(body))
			if err != nil {
				ctrl.responseSetProtocolState400(w, err)
				return
			}
		} else {
			ctrl.responseSetProtocolState400(w, readError)
			return
		}
	} else {
		bodyError := errors.New("Request do not have any body")
		ctrl.responseSetProtocolState400(w, bodyError)
		return
	}
	result := ctrl.handler.SetProtocolState(item, r)
	if result.HasStatusCode200() {
		opts := protojson.MarshalOptions{
			UseProtoNames:   true,
			AllowPartial:    true,
			EmitUnpopulated: true,
			Indent:          "  ",
		}
		data, err := opts.Marshal(result.StatusCode200().Msg())
		if err != nil {
			ctrl.responseSetProtocolState400(w, err)
		}
		httpapi.WriteCustomJSONResponse(w, 200, data)
		return
	}

	if result.HasStatusCode400() {
		httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
		return
	}
	if result.HasStatusCode500() {
		httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
		return
	}
	httpapi.WriteDefaultResponse(w, http.StatusInternalServerError)
}

func (ctrl *controlController) responseSetProtocolState400(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewSetProtocolStateResponse()
	result.StatusCode400().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
}

func (ctrl *controlController) responseSetProtocolState500(w http.ResponseWriter, rsp_err error) {
	result := gosnappi.NewSetProtocolStateResponse()
	result.StatusCode500().SetErrors([]string{rsp_err.Error()})
	httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
}
