// This file is autogenerated. Do not modify
package controllers

import (
	"io/ioutil"
	"net/http"

	gosnappi "github.com/open-traffic-generator/snappi/gosnappi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi"
	"github.com/open-traffic-generator/snappi/gosnappi/httpapi/interfaces"
)

type statesController struct {
	handler interfaces.StatesHandler
}

func NewHttpStatesController(handler interfaces.StatesHandler) interfaces.StatesController {
	return &statesController{handler}
}

func (ctrl *statesController) Routes() []httpapi.Route {
	return []httpapi.Route{
		{Path: "/results/states", Method: "POST", Name: "GetStates", Handler: ctrl.GetStates},
	}
}

/*
GetStates: POST /results/states
Description:
*/
func (ctrl *statesController) GetStates(w http.ResponseWriter, r *http.Request) {
	var item gosnappi.StatesRequest
	if r.Body != nil {
		body, _ := ioutil.ReadAll(r.Body)
		if body != nil {
			item = gosnappi.NewStatesRequest()
			err := item.FromJson(string(body))
			if err != nil {
				item = nil
			}
		}
	}
	result := ctrl.handler.GetStates(item, r)
	if result.HasStatusCode200() {
		httpapi.WriteJSONResponse(w, 200, result.StatusCode200())
		return
	}
	if result.HasStatusCode400() {
		httpapi.WriteJSONResponse(w, 400, result.StatusCode400())
		return
	}
	if result.HasStatusCode500() {
		httpapi.WriteJSONResponse(w, 500, result.StatusCode500())
		return
	}
	httpapi.WriteDefaultResponse(w, http.StatusInternalServerError)
}
